export const bulkGalleryItems = [
  {
    "id": "bulk-1",
    "statueName": "Masterpiece Collection 1",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[460px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_1.avif"
  },
  {
    "id": "bulk-2",
    "statueName": "Masterpiece Collection 2",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[380px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_2.avif"
  },
  {
    "id": "bulk-3",
    "statueName": "Masterpiece Collection 3",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[460px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_3.avif"
  },
  {
    "id": "bulk-4",
    "statueName": "Masterpiece Collection 4",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[380px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_4.avif"
  },
  {
    "id": "bulk-5",
    "statueName": "Masterpiece Collection 5",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[460px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_5.avif"
  },
  {
    "id": "bulk-6",
    "statueName": "Masterpiece Collection 6",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[380px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_6.avif"
  },
  {
    "id": "bulk-7",
    "statueName": "Masterpiece Collection 7",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[460px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_7.avif"
  },
  {
    "id": "bulk-8",
    "statueName": "Masterpiece Collection 8",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[380px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_8.avif"
  },
  {
    "id": "bulk-9",
    "statueName": "Masterpiece Collection 9",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[460px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_9.avif"
  },
  {
    "id": "bulk-10",
    "statueName": "Masterpiece Collection 10",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[380px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_10.avif"
  },
  {
    "id": "bulk-11",
    "statueName": "Masterpiece Collection 11",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[460px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_11.avif"
  },
  {
    "id": "bulk-12",
    "statueName": "Masterpiece Collection 12",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[380px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_12.avif"
  },
  {
    "id": "bulk-13",
    "statueName": "Masterpiece Collection 13",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[460px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_13.avif"
  },
  {
    "id": "bulk-14",
    "statueName": "Masterpiece Collection 14",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[380px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_14.avif"
  },
  {
    "id": "bulk-15",
    "statueName": "Masterpiece Collection 15",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[460px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_15.avif"
  },
  {
    "id": "bulk-16",
    "statueName": "Masterpiece Collection 16",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[380px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_16.avif"
  },
  {
    "id": "bulk-17",
    "statueName": "Masterpiece Collection 17",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[460px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_17.avif"
  },
  {
    "id": "bulk-18",
    "statueName": "Masterpiece Collection 18",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[380px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_18.avif"
  },
  {
    "id": "bulk-19",
    "statueName": "Masterpiece Collection 19",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[460px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_19.avif"
  },
  {
    "id": "bulk-20",
    "statueName": "Masterpiece Collection 20",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[380px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_20.avif"
  },
  {
    "id": "bulk-21",
    "statueName": "Masterpiece Collection 21",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[460px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_21.avif"
  },
  {
    "id": "bulk-22",
    "statueName": "Masterpiece Collection 22",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[380px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_22.avif"
  },
  {
    "id": "bulk-23",
    "statueName": "Masterpiece Collection 23",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[460px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_23.avif"
  },
  {
    "id": "bulk-24",
    "statueName": "Masterpiece Collection 24",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[380px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_24.avif"
  },
  {
    "id": "bulk-25",
    "statueName": "Masterpiece Collection 25",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[460px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_25.avif"
  },
  {
    "id": "bulk-26",
    "statueName": "Masterpiece Collection 26",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[380px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_26.avif"
  },
  {
    "id": "bulk-27",
    "statueName": "Masterpiece Collection 27",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[460px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_27.avif"
  },
  {
    "id": "bulk-28",
    "statueName": "Masterpiece Collection 28",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[380px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_28.avif"
  },
  {
    "id": "bulk-29",
    "statueName": "Masterpiece Collection 29",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[460px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_29.avif"
  },
  {
    "id": "bulk-30",
    "statueName": "Masterpiece Collection 30",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[380px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_30.avif"
  },
  {
    "id": "bulk-31",
    "statueName": "Masterpiece Collection 31",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[460px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_31.avif"
  },
  {
    "id": "bulk-32",
    "statueName": "Masterpiece Collection 32",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[380px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_32.avif"
  },
  {
    "id": "bulk-33",
    "statueName": "Masterpiece Collection 33",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[460px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_33.avif"
  },
  {
    "id": "bulk-34",
    "statueName": "Masterpiece Collection 34",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[380px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_34.avif"
  },
  {
    "id": "bulk-35",
    "statueName": "Masterpiece Collection 35",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[460px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_35.avif"
  },
  {
    "id": "bulk-36",
    "statueName": "Masterpiece Collection 36",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[380px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_36.avif"
  },
  {
    "id": "bulk-37",
    "statueName": "Masterpiece Collection 37",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[460px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_37.avif"
  },
  {
    "id": "bulk-38",
    "statueName": "Masterpiece Collection 38",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[380px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_38.avif"
  },
  {
    "id": "bulk-39",
    "statueName": "Masterpiece Collection 39",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[460px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_39.avif"
  },
  {
    "id": "bulk-40",
    "statueName": "Masterpiece Collection 40",
    "description": "A stunning addition to the Sudarshan Crafts Museum gallery. (Description to be updated)",
    "location": "Sudarshan Gallery",
    "material": "Mixed Media",
    "category": "Stone Sculpture",
    "heightClass": "h-[380px]",
    "placeholderClass": "stone-placeholder-marble",
    "image": "/images/gallery_custom_40.avif"
  }
];
